CREATE TABLE campaign_deposits (
  id SERIAL PRIMARY KEY,
  tier_id VARCHAR(255) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50) DEFAULT 'pending'
);

CREATE TABLE campaign_progress (
  id SERIAL PRIMARY KEY,
  current_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  goal_amount DECIMAL(10,2) NOT NULL DEFAULT 8000,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
